import { Geist, Geist_Mono, Poppins } from "next/font/google";
import "./globals.css";
import Header from "@/components/layout/header";
import Sidebar from "@/components/layout/sidebar";
import { HeaderProvider } from "../context/headerContext";

const poppins = Poppins({
  weight: ["300", "400", "500", "600", "700"],
  style: ["normal", "italic"],
  subsets: ["latin"],
  variable: "--font-poppins",
});

export const metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({ children }) {
  return (
    <html lang="en">
      <body className={` ${poppins.variable} antialiased flex `}>
        <HeaderProvider>
          <div className="flex flex-row w-full ">
            <Sidebar />
            <div className="flex flex-col w-full overflow-y-auto">
              <Header />
              <div className="flex w-full h-full px-6 py-10 overflow-auto">{children}</div>
            </div>
          </div>
        </HeaderProvider>
      </body>
    </html>
  );
}
