import { Poppins } from "next/font/google";
import "./globals.css";
import { HeaderProvider } from "../context/headerContext";
import LayoutWrapper from "@/components/layout/layoutWraper";

const poppins = Poppins({
  weight: ["300", "400", "500", "600", "700"],
  subsets: ["latin"],
  variable: "--font-poppins",
});

export const metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({ children }) {
  return (
    <html lang="en">
      <body className={`${poppins.variable} antialiased`}>
        <HeaderProvider>
          <LayoutWrapper>
            {children}
          </LayoutWrapper>
        </HeaderProvider>
      </body>
    </html>
  );
}
