import { Geist, Geist_Mono, Poppins } from "next/font/google";
import "./globals.css";
import Header from "@/components/layout/header";
import Sidebar from "@/components/layout/sidebar";
import { HeaderProvider } from "../context/headerContext";

const poppins = Poppins({
  weight: ["300", "400", "500", "600", "700"],
  style: ["normal", "italic"],
  subsets: ["latin"],
  variable: "--font-poppins",
});

export const metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({ children }) {
  return (
    <html lang="en">
      <body className={`${poppins.variable} antialiased`}>
        <HeaderProvider>
          
          <div className="fixed left-0 top-0 h-screen w-64  bg-white">
            <Sidebar />
          </div>

          <div className="ml-64 flex flex-col h-screen overflow-hidden ">
            <Header />
            <div className="flex-1 px-6 py-10 overflow-y-auto">
              {children}
            </div>
          </div>

        </HeaderProvider>
      </body>
    </html>
  );
}
